/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.TwitterGUIController;

/**
 *
 * @author emlag
 */
public class TwitterGUI extends javax.swing.JFrame {
    TwitterGUIController myClient;
    
    /**
     * Creates new form TwitterGUI
     */
    public TwitterGUI() {
        initComponents();
        myClient = new TwitterGUIController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        twitterButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        requestTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        responseLabel = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        twitterButton.setText("GetInfo");
        twitterButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                twitterButtonMouseClicked(evt);
            }
        });

        clearButton.setText("Clear");

        requestTextField.setToolTipText("");
        requestTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTextFieldActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(responseLabel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(requestTextField)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(twitterButton)
                        .addGap(106, 106, 106)
                        .addComponent(clearButton))
                    .addComponent(jScrollPane1))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(requestTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(twitterButton)
                    .addComponent(clearButton))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        requestTextField.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void twitterButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_twitterButtonMouseClicked
        
            //send query
            try
            {
                myClient.findUserStats(requestTextField.getText());
//                responseLabel.setText(myClient.getMostPopularWord());
            }
            catch(Exception err)
            {
                responseLabel.setText(err.toString());
            }
            
            //show stats by calling necessary methods
            responseLabel.setText("This user's most popular word is: " + 
            myClient.getMostPopularWord() + ", which appears " +
            myClient.getFrequencyMax() + " times.");
//            responseLabel.setText(myClient.getMostPopularWord());
    }//GEN-LAST:event_twitterButtonMouseClicked

    private void requestTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTextFieldActionPerformed
    // TODO add your handling code here:
    }//GEN-LAST:event_requestTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TwitterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TwitterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TwitterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TwitterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TwitterGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField requestTextField;
    private javax.swing.JTextPane responseLabel;
    private javax.swing.JButton twitterButton;
    // End of variables declaration//GEN-END:variables
}
